# Generated by Django 2.2.3 on 2019-07-19 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Camioneta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente_letra', models.CharField(max_length=50)),
                ('patente_numero', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piso', models.CharField(max_length=50, null=True)),
                ('calle', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('numero_calle', models.CharField(max_length=50)),
                ('id_administracion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='destapacionesposta.Administracion')),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating_general', models.CharField(max_length=50)),
                ('Rating_numers', models.CharField(max_length=50)),
                ('Cant_Rating', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=50)),
                ('contraseña', models.CharField(max_length=50)),
                ('nacimiento', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(max_length=50)),
                ('id_direccion', models.ManyToManyField(to='destapacionesposta.Direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('rating', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='destapacionesposta.Ratings')),
            ],
        ),
        migrations.AddField(
            model_name='ratings',
            name='trabajador1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destapacionesposta.Trabajador'),
        ),
        migrations.CreateModel(
            name='Pedidos_Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_camioneta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destapacionesposta.Camioneta')),
                ('id_direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destapacionesposta.Direccion')),
                ('id_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destapacionesposta.Trabajador')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destapacionesposta.User')),
                ('rating', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='destapacionesposta.Ratings')),
            ],
        ),
        migrations.AddField(
            model_name='administracion',
            name='id_direccion_admin',
            field=models.ManyToManyField(to='destapacionesposta.Direccion'),
        ),
    ]
