# Generated by Django 2.2.3 on 2019-07-12 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destapacionesposta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos_register',
            name='rating',
        ),
    ]
