# Generated by Django 2.2.2 on 2019-06-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destapacionesposta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administracion',
            name='id_direccion_administracion',
        ),
        migrations.AddField(
            model_name='administracion',
            name='id_direccion_admin',
            field=models.ManyToManyField(to='destapacionesposta.Direccion'),
        ),
    ]
