# Generated by Django 2.2.3 on 2019-07-12 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destapacionesposta', '0002_remove_pedidos_register_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedidos_Register',
        ),
    ]
