# Generated by Django 2.2.2 on 2019-06-21 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destapacionesposta', '0002_auto_20190621_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='id_administracion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='destapacionesposta.Administracion'),
        ),
    ]
