# Generated by Django 2.2.3 on 2019-07-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destapacionesposta', '0002_pedidos_register_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='piso',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
