# Generated by Django 2.2.3 on 2019-07-12 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destapacionesposta', '0003_delete_pedidos_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos_Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_camioneta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destapacionesposta.Camioneta')),
                ('id_direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destapacionesposta.Direccion')),
                ('id_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destapacionesposta.Trabajador')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destapacionesposta.User')),
                ('rating', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='destapacionesposta.Ratings')),
            ],
        ),
    ]
