# Generated by Django 2.2.2 on 2019-06-21 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destapacionesposta', '0004_auto_20190621_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos_register',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destapacionesposta.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mail',
            field=models.EmailField(max_length=50),
        ),
    ]
