# Generated by Django 2.2.3 on 2019-07-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destapacionesposta', '0006_pedidos_register_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
